add historical data
OneStarSolution/prometeo pull request #14
Opened 2021-05-21 22:06 UTC by VeroQuizan

Please check the code and help me with your suggestions.

2021-05-21 23:09 UTC, EduardoSantos7 requested changes
Good job Vero!!

I just commented  some improvements.

2021-05-21 23:09 UTC, EduardoSantos7 commented on scripts/addHistorical.py
> +        dataframe_historical = pd.read_csv("../historical_"+source+".csv", delimiter=",",header = None)
Use relative paths is not a good practice, you can change this for the complete path, also as we are in python3 you can use `f` to format strings which is better.

2021-05-21 23:09 UTC, EduardoSantos7 commented on scripts/addHistorical.py
> +        dataframe_historical = pd.read_csv("../historical_"+source+".csv", delimiter=",",header = None)
A style tip: you should separate parameters by comma and space but between equal symbol, you shouldn't add a space (you can install pep8 convention to help you with that)

2021-05-21 23:09 UTC, EduardoSantos7 commented on scripts/addHistorical.py
> +    pd.DataFrame()
why are you creating an empty DataFrame here?

2021-05-21 23:09 UTC, EduardoSantos7 commented on scripts/addHistorical.py
> +        print("Error: ")
When you type except is a good practice to indicate the exceptions expected.

2021-05-21 23:09 UTC, EduardoSantos7 commented on scripts/addHistorical.py
> +    else:
Try, Except, Else bloc is wordy, you didn't need to add else, for example, it's always convenient to decrease indentation levels

2021-05-21 23:09 UTC, EduardoSantos7 commented on scripts/addHistorical.py
> +                historical_col = db.get_historical_bbb()
Actually you can use metaprogramming here but it's ok like that too, just mentioned it in case you want to learn something new

2021-05-21 23:09 UTC, EduardoSantos7 commented on db/PrometeoDB.py
> +        return self.prometeo_db[HISTORICAL_YP]
Those DBS are for phones or URLs?

2021-05-21 23:23 UTC, VeroQuizan commented on db/PrometeoDB.py
> +        return self.prometeo_db[HISTORICAL_YP]
URLS, only the phones has phone numbers

2021-05-21 23:24 UTC, VeroQuizan commented on scripts/addHistorical.py
> +    pd.DataFrame()
For nothing I missed that one

2021-05-21 23:46 UTC, VeroQuizan commented on scripts/addHistorical.py
> +    else:
It's in case of not found file, else has code it will only should be executed if there was no exception.

2021-05-24 17:20 UTC, EduardoSantos7 approved these changes
LGTM

2021-05-28 22:26 UTC, merged